### ISSUE TITLE
Error: rqt_graph is not shown in window

### ISSUE THREAD

**Issue by Moirai** [tork-a/live-cd2#34]
Version 3.0.0 has a problem.
rqt_graph is not shown, occured error is as same as below;
https://answers.ros.org/question/132946/rqt_graph-not-shown-in-window/

Fixed it with one line below in my case.
sudo /usr/bin/pip install --upgrade pydot

Please apply this fix and update live-cd.

**Comment by k-okada** [comment]
thank you for report, the root cause is that (somehow) `pyparse` is installed as pip module, so
`sudo pip uninstall pyparsing` will also work, anyway I'll update the release.
```
ubuntu:~/catkin_ws/src/roscpp_tutorials/roscpp_tutorials/launch$ ls /usr/local/lib/python2.7/dist-packages/
appdirs-1.4.3.dist-info  packaging-16.8.dist-info   pyparsing.pyc
appdirs.py               pip                        setuptools
appdirs.pyc              pip-9.0.1.dist-info        setuptools-35.0.0.dist-info
easy_install.py          pkg_resources              six-1.10.0.dist-info
easy_install.pyc         pyparsing-2.2.0.dist-info  six.py
packaging                pyparsing.py               six.pyc
ubuntu:~/catkin_ws/src/roscpp_tutorials/roscpp_tutorials/launch$ sudo pip uninstall pyparsing
Uninstalling pyparsing-2.2.0:
  /usr/local/lib/python2.7/dist-packages/pyparsing-2.2.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/pyparsing-2.2.0.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/pyparsing-2.2.0.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/pyparsing-2.2.0.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/pyparsing-2.2.0.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/pyparsing-2.2.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/pyparsing.py
  /usr/local/lib/python2.7/dist-packages/pyparsing.pyc
Proceed (y/n)? y
  Successfully uninstalled pyparsing-2.2.0
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
ubuntu:~/catkin_ws/src/roscpp_tutorials/roscpp_tutorials/launch$ rqt_graph            

```

for more information
```
$ rqt_graph
Couldn't import dot_parser, loading of dot files will not be possible.
PluginHandlerDirect._restore_settings() plugin "rqt_graph/RosGraph#0" raised an exception:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 116, in _restore_settings
    self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 203, in restore_settings
    self._refresh_rosgraph()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 227, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 260, in _update_graph_view
    self._redraw_graph_view()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 293, in _redraw_graph_view
    same_label_siblings=True)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_dotgraph/dot_to_qt.py", line 234, in dotcode_to_qt_items
    graph = pydot.graph_from_dot_data(dotcode.encode("ascii", "ignore"))
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 220, in graph_from_dot_data
    return dot_parser.parse_dot_data(data)
NameError: global name 'dot_parser' is not defined

$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dot_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/dot_parser.py", line 25, in <module>
    from pyparsing import ( nestedExpr, Literal, CaselessLiteral, Word, Upcase, OneOrMore, ZeroOrMore,
ImportError: cannot import name Upcase
>>> import pyparsing
>>> from pyparsing import Upcase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Upcase
>>> pyparsing
<module 'pyparsing' from '/usr/local/lib/python2.7/dist-packages/pyparsing.pyc'>
```

**Comment by k-okada** [comment]
@Moirai should be fixed in https://github.com/tork-a/live-cd2/releases/tag/3.0.3

**Comment by Moirai** [comment]
I checked v3.0.3 and confirmed this issue has been fixed．
Thank you for your quickly response!
